# Copyright (c) 2026 SPHARX. All Rights Reserved. "From data intelligence emerges."
# 记忆系统模块间接口定义（协议类）。

from typing import Protocol, List, Dict, Any, Optional, AsyncIterator
import numpy as np
from ..schemas import MemoryRecord, EvolutionReport


class IStorageBackend(Protocol):
    """原始存储后端接口。"""
    async def append(self, data: bytes, metadata: Optional[Dict]) -> str: ...
    async def read(self, location: str) -> Optional[bytes]: ...
    async def delete(self, location: str) -> bool: ...


class IVectorIndex(Protocol):
    """向量索引接口。"""
    async def add(self, ids: List[str], vectors: List[np.ndarray]): ...
    async def search(self, query: np.ndarray, k: int) -> List[tuple[str, float]]: ...
    async def remove(self, ids: List[str]) -> int: ...
    def save(self, path: str): ...
    def load(self, path: str): ...


class IPatternMiner(Protocol):
    """模式挖掘器接口。"""
    async def mine_from_vectors(self, vectors: List[np.ndarray], memory_ids: List[str]) -> List[Any]: ...
    async def get_patterns(self, min_confidence: float) -> List[Any]: ...


class ICommittee(Protocol):
    """委员会接口。"""
    async def analyze_round(self, round_id: str) -> List[Any]: ...
    async def generate_proposals(self) -> List[Any]: ...
    async def submit_finding(self, finding: Any): ...


class IMemoryRovol(Protocol):
    """MemoryRovol 核心接口。"""
    async def write(self, memory: MemoryRecord) -> str: ...
    async def retrieve(self, query_vector: np.ndarray, k: int) -> List[MemoryRecord]: ...
    async def bind(self, memory_ids: List[str], relation: str) -> Optional[np.ndarray]: ...
    async def evolve(self) -> EvolutionReport: ...
    async def forget(self, memory_ids: Optional[List[str]] = None): ...