# CMake generated Testfile for 
# Source directory: D:/SPHARX-CN/SpharxWorks/AgentOS/agentos/atoms/syscall
# Build directory: D:/SPHARX-CN/SpharxWorks/AgentOS/build_test/agentos/atoms/syscall
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[test_syscall_entry]=] "D:/SPHARX-CN/SpharxWorks/AgentOS/build_test/agentos/atoms/syscall/Debug/test_syscall_entry.exe")
  set_tests_properties([=[test_syscall_entry]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/SPHARX-CN/SpharxWorks/AgentOS/agentos/atoms/syscall/CMakeLists.txt;97;add_test;D:/SPHARX-CN/SpharxWorks/AgentOS/agentos/atoms/syscall/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[test_syscall_entry]=] "D:/SPHARX-CN/SpharxWorks/AgentOS/build_test/agentos/atoms/syscall/Release/test_syscall_entry.exe")
  set_tests_properties([=[test_syscall_entry]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/SPHARX-CN/SpharxWorks/AgentOS/agentos/atoms/syscall/CMakeLists.txt;97;add_test;D:/SPHARX-CN/SpharxWorks/AgentOS/agentos/atoms/syscall/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[test_syscall_entry]=] "D:/SPHARX-CN/SpharxWorks/AgentOS/build_test/agentos/atoms/syscall/MinSizeRel/test_syscall_entry.exe")
  set_tests_properties([=[test_syscall_entry]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/SPHARX-CN/SpharxWorks/AgentOS/agentos/atoms/syscall/CMakeLists.txt;97;add_test;D:/SPHARX-CN/SpharxWorks/AgentOS/agentos/atoms/syscall/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[test_syscall_entry]=] "D:/SPHARX-CN/SpharxWorks/AgentOS/build_test/agentos/atoms/syscall/RelWithDebInfo/test_syscall_entry.exe")
  set_tests_properties([=[test_syscall_entry]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/SPHARX-CN/SpharxWorks/AgentOS/agentos/atoms/syscall/CMakeLists.txt;97;add_test;D:/SPHARX-CN/SpharxWorks/AgentOS/agentos/atoms/syscall/CMakeLists.txt;0;")
else()
  add_test([=[test_syscall_entry]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[test_syscall_table]=] "D:/SPHARX-CN/SpharxWorks/AgentOS/build_test/agentos/atoms/syscall/Debug/test_syscall_table.exe")
  set_tests_properties([=[test_syscall_table]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/SPHARX-CN/SpharxWorks/AgentOS/agentos/atoms/syscall/CMakeLists.txt;109;add_test;D:/SPHARX-CN/SpharxWorks/AgentOS/agentos/atoms/syscall/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[test_syscall_table]=] "D:/SPHARX-CN/SpharxWorks/AgentOS/build_test/agentos/atoms/syscall/Release/test_syscall_table.exe")
  set_tests_properties([=[test_syscall_table]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/SPHARX-CN/SpharxWorks/AgentOS/agentos/atoms/syscall/CMakeLists.txt;109;add_test;D:/SPHARX-CN/SpharxWorks/AgentOS/agentos/atoms/syscall/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[test_syscall_table]=] "D:/SPHARX-CN/SpharxWorks/AgentOS/build_test/agentos/atoms/syscall/MinSizeRel/test_syscall_table.exe")
  set_tests_properties([=[test_syscall_table]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/SPHARX-CN/SpharxWorks/AgentOS/agentos/atoms/syscall/CMakeLists.txt;109;add_test;D:/SPHARX-CN/SpharxWorks/AgentOS/agentos/atoms/syscall/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[test_syscall_table]=] "D:/SPHARX-CN/SpharxWorks/AgentOS/build_test/agentos/atoms/syscall/RelWithDebInfo/test_syscall_table.exe")
  set_tests_properties([=[test_syscall_table]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/SPHARX-CN/SpharxWorks/AgentOS/agentos/atoms/syscall/CMakeLists.txt;109;add_test;D:/SPHARX-CN/SpharxWorks/AgentOS/agentos/atoms/syscall/CMakeLists.txt;0;")
else()
  add_test([=[test_syscall_table]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[test_full_workflow]=] "D:/SPHARX-CN/SpharxWorks/AgentOS/build_test/agentos/atoms/syscall/Debug/test_full_workflow.exe")
  set_tests_properties([=[test_full_workflow]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/SPHARX-CN/SpharxWorks/AgentOS/agentos/atoms/syscall/CMakeLists.txt;122;add_test;D:/SPHARX-CN/SpharxWorks/AgentOS/agentos/atoms/syscall/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[test_full_workflow]=] "D:/SPHARX-CN/SpharxWorks/AgentOS/build_test/agentos/atoms/syscall/Release/test_full_workflow.exe")
  set_tests_properties([=[test_full_workflow]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/SPHARX-CN/SpharxWorks/AgentOS/agentos/atoms/syscall/CMakeLists.txt;122;add_test;D:/SPHARX-CN/SpharxWorks/AgentOS/agentos/atoms/syscall/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[test_full_workflow]=] "D:/SPHARX-CN/SpharxWorks/AgentOS/build_test/agentos/atoms/syscall/MinSizeRel/test_full_workflow.exe")
  set_tests_properties([=[test_full_workflow]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/SPHARX-CN/SpharxWorks/AgentOS/agentos/atoms/syscall/CMakeLists.txt;122;add_test;D:/SPHARX-CN/SpharxWorks/AgentOS/agentos/atoms/syscall/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[test_full_workflow]=] "D:/SPHARX-CN/SpharxWorks/AgentOS/build_test/agentos/atoms/syscall/RelWithDebInfo/test_full_workflow.exe")
  set_tests_properties([=[test_full_workflow]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/SPHARX-CN/SpharxWorks/AgentOS/agentos/atoms/syscall/CMakeLists.txt;122;add_test;D:/SPHARX-CN/SpharxWorks/AgentOS/agentos/atoms/syscall/CMakeLists.txt;0;")
else()
  add_test([=[test_full_workflow]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[test_syscall_extended]=] "D:/SPHARX-CN/SpharxWorks/AgentOS/build_test/agentos/atoms/syscall/Debug/test_syscall_extended.exe")
  set_tests_properties([=[test_syscall_extended]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/SPHARX-CN/SpharxWorks/AgentOS/agentos/atoms/syscall/CMakeLists.txt;135;add_test;D:/SPHARX-CN/SpharxWorks/AgentOS/agentos/atoms/syscall/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[test_syscall_extended]=] "D:/SPHARX-CN/SpharxWorks/AgentOS/build_test/agentos/atoms/syscall/Release/test_syscall_extended.exe")
  set_tests_properties([=[test_syscall_extended]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/SPHARX-CN/SpharxWorks/AgentOS/agentos/atoms/syscall/CMakeLists.txt;135;add_test;D:/SPHARX-CN/SpharxWorks/AgentOS/agentos/atoms/syscall/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[test_syscall_extended]=] "D:/SPHARX-CN/SpharxWorks/AgentOS/build_test/agentos/atoms/syscall/MinSizeRel/test_syscall_extended.exe")
  set_tests_properties([=[test_syscall_extended]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/SPHARX-CN/SpharxWorks/AgentOS/agentos/atoms/syscall/CMakeLists.txt;135;add_test;D:/SPHARX-CN/SpharxWorks/AgentOS/agentos/atoms/syscall/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[test_syscall_extended]=] "D:/SPHARX-CN/SpharxWorks/AgentOS/build_test/agentos/atoms/syscall/RelWithDebInfo/test_syscall_extended.exe")
  set_tests_properties([=[test_syscall_extended]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/SPHARX-CN/SpharxWorks/AgentOS/agentos/atoms/syscall/CMakeLists.txt;135;add_test;D:/SPHARX-CN/SpharxWorks/AgentOS/agentos/atoms/syscall/CMakeLists.txt;0;")
else()
  add_test([=[test_syscall_extended]=] NOT_AVAILABLE)
endif()
